lib/ketbin_web/router.ex
defmodule KetbinWeb.Router do
  use KetbinWeb, :router

  import KetbinWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_current_user
  end

  # scope to ensure user is authenticated
  scope "/", KetbinWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/pastes", PageController, :pastes
  end

  scope "/", KetbinWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/:id/raw", PageController, :raw

    post "/", PageController, :create
  end

  # scope to check if user is owner of paste
  scope "/", KetbinWeb do
    pipe_through [:browser, :owns_paste]

    get "/:id", PageController, :show
    get "/v/:id", PageController, :showlink
  end

  # scope to ensure user is owner of paste
  scope "/", KetbinWeb do
    pipe_through [:browser, :ensure_owns_paste]

    get "/edit/:id", PageController, :edit
    patch "/:id", PageController, :update
    put "/:id", PageController, :update
  end

  scope "/api", KetbinWeb.Api, as: :api do
    pipe_through :api

    resources "/paste", PasteController, only: [:show, :index, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", KetbinWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: KetbinWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", KetbinWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", KetbinWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", KetbinWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm

  end
end

lib/ketbin/pastes.ex
defmodule Ketbin.Pastes do
  @moduledoc """
  The Pastes context.
  """

  import Ecto.Query, warn: false
  alias Ketbin.Repo

  alias Ketbin.Pastes.Paste

  @doc """
  Returns the list of pastes.

  ## Examples

      iex> list_pastes()
      [%Paste{}, ...]

  """
  def list_pastes do
    Repo.all(Paste)
  end

  def list_pastes_by_user(user_id) do
    Repo.all(from(p in Paste, where: p.belongs_to == ^user_id))
  end

  @doc """
  Gets a single paste.

  Raises `Ecto.NoResultsError` if the Paste does not exist.

  ## Examples

      iex> get_paste!(123)
      %Paste{}

      iex> get_paste!(456)
      ** (Ecto.NoResultsError)

  """
  def get_paste!(id), do: Repo.get!(Paste, id)

  @doc """
  Creates a paste.

  ## Examples

      iex> create_paste(%{field: value})
      {:ok, %Paste{}}

      iex> create_paste(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_paste(attrs \\ %{}) do
    %Paste{}
    |> Paste.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a paste.

  ## Examples

      iex> update_paste(paste, %{field: new_value})
      {:ok, %Paste{}}

      iex> update_paste(paste, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_paste(%Paste{} = paste, attrs) do
    paste
    |> Paste.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a paste.

  ## Examples

      iex> delete_paste(paste)
      {:ok, %Paste{}}

      iex> delete_paste(paste)
      {:error, %Ecto.Changeset{}}

  """
  def delete_paste(%Paste{} = paste) do
    Repo.delete(paste)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking paste changes.

  ## Examples

      iex> change_paste(paste)
      %Ecto.Changeset{data: %Paste{}}

  """
  def change_paste(%Paste{} = paste, attrs \\ %{}) do
    Paste.changeset(paste, attrs)
  end
end

lib/ketbin/pastes/paste.ex
defmodule Ketbin.Pastes.Paste do
  use Ecto.Schema
  import Ecto.Changeset
  @derive {Jason.Encoder, only: [:content, :is_url, :belongs_to]}

  @primary_key {:id, :string, autogenerate: false}
  @derive {Phoenix.Param, key: :id}
  schema "pastes" do
    field :content, :string
    field :is_url, :boolean, default: false
    field :belongs_to, :id

    timestamps()
  end

  @doc false
  def changeset(paste, attrs) do
    paste
    |> cast(attrs, [:is_url, :content, :id, :belongs_to])
    |> validate_required([:is_url, :content])
    |> unique_constraint(:id, name: :pastes_pkey)
  end
end

lib/ketbin/pastes/utils.ex
defmodule Ketbin.Pastes.Utils do
  defp rand_vowel do
    String.graphemes("aeiou")
    |> Enum.take_random(1)
    |> Enum.at(0)
  end

  defp rand_consonant do
    String.graphemes("bcdfghjklmnpqrstvwxyz")
    |> Enum.take_random(1)
    |> Enum.at(0)
  end

  def generate_key(length \\ 10) do
    random = Enum.random([0, 1])

    Enum.map(0..length, fn i ->
      if Integer.mod(i, 2) == random, do: rand_consonant(), else: rand_vowel()
    end)
    |> List.to_string()
  end

  def is_url?(url) do
    try do
      uri = URI.parse(url)

      uri.scheme != nil && uri.host =~ "." &&
        Enum.member?(["https", "http", "mailto"], uri.scheme) && !(uri.host =~ "katb.in")
    rescue
      FunctionClauseError -> false
    end
  end
end

lib/ketbin_web/controllers/api/paste_controller.ex
defmodule KetbinWeb.Api.PasteController do
  use KetbinWeb, :controller

  alias Ketbin.Pastes
  alias Ketbin.Pastes.Utils

  def show(conn, %{"id" => id}) do
    [head | _tail] = String.split(id, ".")

    # fetch paste from db
    paste = Pastes.get_paste!(head)
    render(conn, "paste.json", paste: paste)
  end

  def create(%{assigns: %{current_user: current_user}} = conn, %{"paste" => paste_params}) do
    # generate phonetic key
    id = Utils.generate_key()

    # check if content is a url
    is_url =
      Map.get(paste_params, "content")
      |> Utils.is_url?()

    # put id and is_url values into changeset
    paste_params =
      Map.put(paste_params, "id", id)
      |> Map.put("is_url", is_url)
      |> Map.put("belongs_to", current_user && current_user.id)

    # attempt to create a paste
    case Pastes.create_paste(paste_params) do
      # all good
      {:ok, paste} ->
        conn
        |> put_status(:created)
        |> render("paste.json", paste: paste)

      # something went wrong, bail
      {:error, %Ecto.Changeset{} = _changeset} ->
        conn
        |> put_status(:internal_server_error)
        |> render("error.json")
    end
  end
end

lib/ketbin_web/templates/paste/edit.html.eex
<h1>Edit Paste</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.paste_path(@conn, :update, @paste)) %>

<span><%= link "Back", to: Routes.paste_path(@conn, :index) %></span>

lib/ketbin_web/templates/paste/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :is_url %>
  <%= checkbox f, :is_url %>
  <%= error_tag f, :is_url %>

  <%= label f, :content %>
  <%= textarea f, :content %>
  <%= error_tag f, :content %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/ketbin_web/templates/paste/index.html.eex
<h1>Listing Pastes</h1>

<table>
  <thead>
    <tr>
      <th>Is url</th>
      <th>Content</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for paste <- @pastes do %>
    <tr>
      <td><%= paste.is_url %></td>
      <td><%= paste.content %></td>

      <td>
        <span><%= link "Show", to: Routes.paste_path(@conn, :show, paste) %></span>
        <span><%= link "Edit", to: Routes.paste_path(@conn, :edit, paste) %></span>
        <span><%= link "Delete", to: Routes.paste_path(@conn, :delete, paste), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Paste", to: Routes.paste_path(@conn, :new) %></span>

lib/ketbin_web/templates/paste/new.html.eex
<%= render "form.html", Map.put(assigns, :action, Routes.paste_path(@conn, :create)) %>

lib/ketbin_web/templates/paste/show.html.eex
<h1>Show Paste</h1>

<ul>

  <li>
    <strong>Is url:</strong>
    <%= @paste.is_url %>
  </li>

  <li>
    <strong>Content:</strong>
    <%= @paste.content %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.paste_path(@conn, :edit, @paste) %></span>
<span><%= link "Back", to: Routes.paste_path(@conn, :index) %></span>